version: 2
jobs:
  build:
    docker:
      # In advanced project settings one can set private variables such as the docker username and password
      #- image: bakerb845/mkl-iscl-build
      #  auth:
      #     username: $DOCKER_USER
      #     password: $DOCKER_PASS
      #- image: bakerb845/ubuntu-rtseis
      - image: bakerb845/rtseis_ubuntu22
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Configure the code
          command: |
            export IPP_ROOT=/opt/intel/ipp
            export MKL_ROOT=/opt/intel/mkl
            export GTEST_ROOT=/usr/local
            export BUILD_DIR=build
            if [ -d ${BUILD_DIR} ]; then
               echo "Removing build directory" ${BUILD_DIR}
               rm -rf ${BUILD_DIR}
            fi
            mkdir ${BUILD_DIR}
            cd ${BUILD_DIR}
            cmake .. \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_C_FLAGS="-Wall"
            #\
            #-DCMAKE_CXX_FLAGS="-Wall" \
            #-DRTSEIS_WRAP_PYTHON=ON \
            #-Dpybind11_INCLUDE_DIR="/usr/local/include/pybind11"
      - run:
           name: Build the code
           command: |
            cd build
            make
      - run:
           name: Test the code
           command: |
            cd build
            ctest --verbose
